site_name: "UNLV Smart Cities REU 2021"
site_description: "Smart Parking Application"
site_url: "https://lazeroffmichael.github.io/smart-park/"
repo_url: "https://github.com/lazeroffmichael/smart-park"
repo_name: "lazeroffmichael/smart-park"


nav:
  - Overview: index.md
  - Components:
    - Data Simulation: data.md
    - Model: model.md
    - Cloud: cloud.md
    - App: app.md
theme:
  name: "material"
  palette:
    primary:
      blue
  features:
    - navigation.instant
    - toc.integrate

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              rendering:
                  show_source: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
